### PR TITLE
Update jafama to the latest Java and add Gradle

### PR DESCRIPTION
**Pull request by ghost**
This pull request updates jafama to work with the latest Java (8/9) and allows building and use with grade. This also adds a template for travis ci builds.

### CODE REVIEW

**Comment by rogersachan** [comment]
@jeffhain Please let me know if I have to sign any CLA

**Comment by jeffhain** [comment]
Hello, and thank you for proposing upgrades to Jafama.


About working with Java 8/9:

Jafama should already work properly (jar usable, and source compilable) with these, as it does with Java 5 to 7, since it only uses very basic non-deprecated language features (static methods, primitive types, etc.).


About adding support to IntelliJ/Gradle/Travis:

I don't want to tie Jafama with any third-party tooling, it's aimed at containing only the "pure" sources, plus eventually some code to generate the jar in a reproductible and self-reliable way using JDK internal tools.
Even if there was only one IDE and build tool in the world, I would not do it, and there are hundreds. I use Eclipse myself, and didn't add .project or .classpath files.
Just forking Jafama and adding the files for your tooling of choice should be the right way to go.


About code reformating:

Your changes correspond to my current formatting style (spaces in for loops definitions, etc.), so I might piggyback this along with other (more featuresque) modifications for another version of Jafama (maybe for Java 9, as a module? I have no plan yet).


About creating a CHANGELOG.txt file:

That's a good idea, the README should just be an introduction to latest version.
As for reformating, I could do it for a new version.


About using Markdown for README:

I'm a simplicity fanatic, so while I might (or might not!) use .md format to help make a large file more readable, I don't think I'll use it for something as simple as a README ought to be. Unless maybe I'm the only one left in the world using .txt, but even then, I think I would stick to it.


So as a result of all this I won't pull your changes into Jafama.
Also currently I'm working on some other and big thing, and I feel like a context-switch would require me as much energy as for a diplodocus to turn back.
Hoping that doesn't disappoint you too much!


-Jeff

**Comment by jeffhain** [comment]
Hi.Replied to you on github.-Jeff

      De : Roger <notifications@github.com>
 À : jeffhain/jafama <jafama@noreply.github.com> 
Cc : jeffhain <jeffhain@rocketmail.com>; Mention <mention@noreply.github.com>
 Envoyé le : Samedi 2 septembre 2017 19h25
 Objet : Re: [jeffhain/jafama] Update jafama to the latest Java and add Gradle (#3)
   
@jeffhain Please let me know if I have to sign any CLA—

**Comment by ghost** [comment]
Thanks for letting me know!

**Comment by rogersachan** [comment]
I just want to note regarding the IntelliJ/Gradle/TravisCI that what I did to the code did not make it dependent on any of those pieces of software.

If you look at the final diff, you'll see that all I did was add a config gradle file and TravisCI file to the source. All this does is make it easier for an IDE to recognize and test the code and to that extent - allows TravisCI to recognize it.

**Pull request closed without merging**
